apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgres-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim

      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage #must be the same name we define up in the volumes array
              mountPath: /var/lib/postgresql/data #here we need to tell it which which folder we need to backup or store in that volume and for postgres is
              #this path
              subPath: postgres #this option is only for time we using 'postgres' and here we saying in that volume store data in a
              #folder call 'postgres'
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
